version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=v
      - RABBITMQ_DEFAULT_PASS=123456
    command: sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
    restart: on-failure

  auth:
    image: authservice
    ports:
      - 3010:3010
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - LINESERVICE=http://192.168.56.110:3002/api_Line
      - NETWORKSERVICE=http://192.168.56.110:3003/api_network
      - POLLARSERVICE=http://192.168.56.110:3001/api_Pollar
      - COLLUMNSERVICE=http://192.168.56.110:3006/api_column
      - DEPENDANCYSERVICE=http://192.168.56.110:3004/api_DependancyWheel
      - MYDIAGRAMSSERVICE=http://192.168.56.110:3008/api_Mydiagrams
      - PURCHASESERVCIE=http://192.168.56.110:3011/api_purchase
      - LINEANNOTATIONSERVICE=http://192.168.56.110:3005/api_LineAnotations
      - Base_Url=192.168.56.110
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure
  pollar:
    image: pollarservice
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
      - auth_service=http://192.168.56.110:3010
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
      - Base_Url=192.168.56.110
    restart: on-failure

  collumn:
    image: collumnservice
    ports:
      - 3006:3006
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
      - auth_service=http://192.168.56.110:3010
      - Base_Url=192.168.56.110
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure
  depedencywheel:
    image: depedencywheel
    ports:
      - 3004:3004
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
      - auth_service=http://192.168.56.110:3010
      - Base_Url=192.168.56.110
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure
  line:
    image: lineservice
    ports:
      - 3002:3002
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - auth_service=http://192.168.56.110:3010
      - Base_Url=192.168.56.110
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  network:
    image: networkservice
    ports:
      - 3003:3003
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - auth_service=http://192.168.56.110:3010
      - Base_Url=192.168.56.110
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  eCharts:
    image: echarts
    ports:
      - 4007:4007


  upload:
    image: upload
    ports:
      - 3000:3000
    mem_limit: 200M
    environment:
      - auth_service=http://192.168.56.110:3010
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure
      
  myDiagrams:
    image: mydiagrams
    ports:
      - 3008:3008
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
     - auth_service=http://192.168.56.110:3010
     - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  purchaseService:
    image: purchaseservice
    ports:
      - 3011:3011
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - auth_service=http://192.168.56.110:3010
      - Base_Url=192.168.56.110
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  donwloadSvg:
    image: donwloadsvg
    ports:
      - 3012:3012
    depends_on:
      - rabbitmq
    volumes:
      - svgFiles:/app/utils/Files/svg
    mem_limit: 200M
    environment:
       - auth_service=http://192.168.56.110:3010/
       - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  donwloadPdf:
    image: donwloadpdf
    ports:
      - 3013:3013
    depends_on:
      - rabbitmq
    volumes:
      - pdfFiles:/app/utils/Files/pdf
    mem_limit: 200M
    environment:
       - auth_service=http://192.168.56.110:3010/
       - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  donwloadPng:
    image: donwloadpng
    ports:
      - 3014:3014
    depends_on:
      - rabbitmq
    volumes:
      - pngFiles:/app/utils/Files/png
    mem_limit: 200M
    environment:
      - auth_service=http://192.168.56.110:3010/
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  donwloadHtml:
    image: donwloadhtml
    ports:
      - 3015:3015
    depends_on:
      - rabbitmq
    volumes:
      - htmlFiles:/app/utils/Files/html
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
      - auth_service=http://192.168.56.110:3010/
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure

  redis:
    image: redis
    ports:
      - 6379:6379
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
    restart: on-failure

  lineannotations:
    image: lineannotationsservice
    ports:
      - 3005:3005
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
      - RABBITMQ_URL=amqp://v:123456@192.168.56.110:5672
    restart: on-failure



  demo:
    image: demoservice
    ports:
      - 3016:3016
    volumes:
      - csvFiles:/app/utils/Files/csv
    mem_limit: 200M
    restart: on-failure

volumes:
  svgFiles:
  pdfFiles:
  pngFiles:
  htmlFiles:
  csvFiles:
