version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=v
      - RABBITMQ_DEFAULT_PASS=123456
    command: sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"

  auth:
    image: authservice
    ports:
      - 3010:3010
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  pollar:
    image: pollarservice
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  collumn:
    image: collumnservice
    ports:
      - 3006:3006
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  depedencywheel:
    image: depedencywheel
    ports:
      - 3004:3004
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  line:
    image: lineservice
    ports:
      - 3002:3002
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  network:
    image: networkservice
    ports:
      - 3003:3003
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  eCharts:
    image: echarts
    ports:
      - 4007:4007
    environment:
      - BASE_URL=192.168.0.200

  upload:
    image: upload
    ports:
      - 3000:3000
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  myDiagrams:
    image: mydiagrams
    ports:
      - 3008:3008
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  purchaseService:
    image: purchaseservice
    ports:
      - 3011:3011
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  donwloadSvg:
    image: donwloadsvg
    ports:
      - 3012:3012
    depends_on:
      - rabbitmq
    volumes:
      - svgFiles:/app/utils/Files/svg
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  donwloadPdf:
    image: donwloadpdf
    ports:
      - 3013:3013
    depends_on:
      - rabbitmq
    volumes:
      - pdfFiles:/app/utils/Files/pdf
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  donwloadPng:
    image: donwloadpng
    ports:
      - 3014:3014
    depends_on:
      - rabbitmq
    volumes:
      - pngFiles:/app/utils/Files/png
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  donwloadHtml:
    image: donwloadhtml
    ports:
      - 3015:3015
    depends_on:
      - rabbitmq
    volumes:
      - htmlFiles:/app/utils/Files/html
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  redis:
    image: redis
    ports:
      - 6379:6379
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  lineannotations:
    image: lineannotationsservice
    ports:
      - 3005:3005
    depends_on:
      - rabbitmq
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  authdb:
    image: mongo
    container_name: authdb
    ports:
      - 27017:27017
    volumes:
      - authdb_data:/data/db

  mydiagramsdb:
    image: mongo
    container_name: mydiagramsdb
    ports:
      - 27020:27017
    volumes:
      - myDiagramsdbData:/data/db

  downloadSvgMongo:
    image: mongo
    container_name: downloadsvgmongo
    ports:
      - 27018:27017
    volumes:
      - downloadSvgMongoData:/data/db
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  downloadPngMongo:
    image: mongo
    container_name: downloadpngmongo
    ports:
      - 27019:27017
    volumes:
      - downloadPngMongoData:/data/db
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  purchaseLogMongo:
    image: mongo
    container_name: purchaselogmongo
    ports:
      - 27021:27017
    volumes:
      - purchaseLogMongoData:/data/db
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  downloadHtmlMongo:
    image: mongo
    container_name: downloadhtmlmongo
    ports:
      - 27022:27017
    volumes:
      - downloadHtmlMongoData:/data/db
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200

  downloadPdfMongo:
    image: mongo
    container_name: downloadpdfmongo
    ports:
      - 27023:27017
    volumes:
      - downloadPdfMongoData:/data/db
    mem_limit: 200M
    environment:
      - BASE_URL=192.168.0.200
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=authdb
      - ME_CONFIG_MONGODB_PORT=27017
    mem_limit: 200M
  demo:
    image: demoservice
    ports:
      - 3016:3016
    volumes:
      - csvFiles:/app/utils/Files/csv
    mem_limit: 200M
volumes:
  svgFiles:
  pdfFiles:
  pngFiles:
  htmlFiles:
  csvFiles:
  authdb_data:
  downloadSvgMongoData:
  downloadPngMongoData:
  myDiagramsdbData:
  purchaseLogMongoData:
  downloadHtmlMongoData:
  downloadPdfMongoData:
